# config.py
ALPHA_VANTAGE_API_KEY = "YOUR_ALPHA_VANTAGE_API_KEY_HERE"
STOCK_SYMBOLS = ["RELIANCE.BSE", "HDFCBANK.BSE", "INFY.BSE"]
GOOGLE_SHEET_KEY_PATH = "credentials.json"
GOOGLE_SHEET_TITLE = "Algo Trading Report"
TELEGRAM_BOT_TOKEN = "YOUR_FULL_TELEGRAM_BOT_TOKEN_HERE"
TELEGRAM_CHAT_ID = "YOUR_NUMERICAL_TELEGRAM_CHAT_ID_HERE"
